from .dog_wtw_lite import DogWTWLight
from .dog_wtw_lite_config import (
    DogWTWLightACfg,
    DogWTWLightAPPOCfg,
    DogWTWLightBCfg,
    DogWTWLightBPPOCfg,
    DogWTWLightCCfg,
    DogWTWLightCPPOCfg,
    DogWTWLightCMass137Cfg,
    DogWTWLightCMass137PPOCfg,
    DogWTWLightCMass137Clearance3Cfg,
    DogWTWLightCMass137Clearance3PPOCfg,
    DogWTWLightOriginal17Contact2Cfg,
    DogWTWLightOriginal17Contact2PPOCfg,
    DogWTWLightOriginal23Contact2Cfg,
    DogWTWLightOriginal23Contact2PPOCfg,
    DogWTWLightCStable2Cfg,
    DogWTWLightCStable2PPOCfg,
    DogWTWLightCStable3RaibertCfg,
    DogWTWLightCStable3RaibertPPOCfg,
    DogWTWLightCStable4Cfg,
    DogWTWLightCStable4PPOCfg,
    DogWTWLightCSlow010Cfg,
    DogWTWLightCSlow010PPOCfg,
    DogWTWLightDCfg,
    DogWTWLightDPPOCfg,
)
